{% set name = "azure-c-shared-utility" %}
{% set version = "2020.01.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Azure/azure-c-shared-utility/archive/{{ version.replace('.', '-') }}.tar.gz
    sha256: 643f3b84ac511b301e481c35278e6a4deacb9e945ad1e36dc3ff4b5f45300b39

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [linux]
    - cmake
    - make   # [not win]
    - ninja  # [win]
  host:
    - azure-macro-utils-c <2020.10.29
    - libuuid  # [unix]
    - umock-c
  run:
    - azure-macro-utils-c <2020.10.29
    - umock-c

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\aziotsharedutil.dll exit 1  # [win]
    - test -f "${PREFIX}/lib/libaziotsharedutil.${SHLIB_EXT}"  # [not win]

about:
  home: https://github.com/Azure/azure-c-shared-utility
  license: MIT
  license_file: LICENSE
  summary: |
    Azure C Shared Utility

extra:
  recipe-maintainers:
    - xylar
    - seanyen
